apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testing
  name: testing
spec:
  containers:
  - image: busybox
    name: testing
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
